"""Storage adapter protocol and base types."""

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class StorageAdapter(Protocol):
    """
    Protocol that all storage adapters must implement.
    
    This defines the contract between the Storage Manager and specific
    storage implementations. All adapters must support these operations
    for their respective memory types.
    
    Design Principles:
    - Namespace isolation is MANDATORY - all operations filter by namespace
    - Errors raise StorageError with context
    - All operations are async (non-blocking I/O)
    - Return types are consistent across implementations
    """

    async def store(
        self,
        memory_id: UUID,
        namespace: str,
        data: Dict[str, Any],
        embedding: Optional[List[float]],
        metadata: Dict[str, Any],
    ) -> UUID:
        """
        Store a memory in the backend.
        
        Args:
            memory_id: Unique identifier (generated by Storage Manager)
            namespace: Isolation key (format: "tenant:X:user:Y" or similar)
            data: Memory data (structure depends on memory type)
            embedding: Optional vector embedding (for LONG_TERM only)
            metadata: Additional metadata (tags, timestamp, etc.)
            
        Returns:
            memory_id: Confirmation of stored ID
            
        Raises:
            StorageError: If storage operation fails
            
        Notes:
            - MUST enforce namespace isolation
            - MUST validate required fields in data
            - MUST log operation for observability
        """
        ...

    async def retrieve(
        self,
        namespace: str,
        query: Optional[str],
        filters: Optional[Dict[str, Any]],
        limit: int,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve memories matching query and filters.
        
        Args:
            namespace: Isolation key (MUST filter results)
            query: Optional search query (text search or vector similarity)
            filters: Optional metadata filters (exact match)
            limit: Maximum results to return
            
        Returns:
            List of memories with metadata and scores
            
        Format:
            [
                {
                    "memory_id": "uuid-string",
                    "memory_type": "WORKING",
                    "namespace": "tenant:1:user:123",
                    "data": {...},
                    "metadata": {...},
                    "score": 0.95,  # relevance (optional)
                    "created_at": "2025-10-04T12:00:00Z"
                },
                ...
            ]
            
        Notes:
            - MUST filter by namespace (no cross-tenant leakage)
            - Return empty list if no matches (don't raise)
            - Results should be sorted (relevance or time)
        """
        ...

    async def get(
        self,
        memory_id: UUID,
        namespace: str,
    ) -> Optional[Dict[str, Any]]:
        """
        Get specific memory by ID.
        
        Args:
            memory_id: Memory identifier
            namespace: Isolation key (for authorization)
            
        Returns:
            Memory data or None if not found or wrong namespace
            
        Notes:
            - Must verify namespace matches (security)
            - Return None (don't raise) if not found
        """
        ...

    async def delete(
        self,
        memory_id: UUID,
        namespace: str,
    ) -> bool:
        """
        Delete a memory.
        
        Args:
            memory_id: Memory identifier
            namespace: Isolation key (for authorization)
            
        Returns:
            True if deleted, False if not found
            
        Notes:
            - Must verify namespace matches
            - Idempotent (delete twice = no error)
        """
        ...

    async def health_check(self) -> Dict[str, Any]:
        """
        Check health of storage backend.
        
        Returns:
            Dictionary with status information:
            {
                "status": "connected" | "error",
                "latency_ms": 10.5,
                "memory_count": 1234,
                "error": "error message if status=error"
            }
            
        Notes:
            - Should be fast (< 100ms)
            - Used for readiness checks
            - Don't raise exceptions (return error status)
        """
        ...
